### ISSUE TITLE
goToLimitAndSetAsHome and limit switch

### ISSUE THREAD

**Issue by vitalibr** [pkerspe/ESP-FlexyStepper#20]
hi!

I'm trying to understand the code to understand how this function goToLimitAndSetAsHome uses the limit switch if there is no way to inform the limit switch pin.

I was using the moveToHomeInSteps, but goToLimitAndSetAsHome is a non block function (better for me).
Do I need to check the limit switch in my main loop the same way in this example? https://github.com/pkerspe/ESP-FlexyStepper/blob/master/examples/Example4_Limit_and_latching_EmergencySwitch/Example4_Limit_and_latching_EmergencySwitch.ino

**Comment by vitalibr** [comment]
Ok, so probably I need to use setLimitSwitchActive in my main loop to trigger the limit switch for the ESP-FlexyStepper

**Comment by pkerspe** [comment]
Example [4 limit and latching EmergenccySwitch](https://github.com/pkerspe/ESP-FlexyStepper/tree/master/examples/Example4_Limit_and_latching_EmergencySwitch) shows how to use Limit Switches as you figured out already.
The limit switch handling (direct PIN configuration, interrupt handling etc.) has not been integrated into the library itself since it would require a somewhat exclusive use the io pins where the limit switches are connected to.
If you have two ore more stepper instances you would need two (or more) IO pins (one for each stepper instance) to act as limit switch, which in some use cases might be no problem, but if you want to chain (wire in serial) multiple limit switches and connect all to a single IO Pin to save pins, this would most likely lead to issues when multiple stepper instances configured, read and register interrupt handlers to the same IO pin.
